coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 0%
        informational: true
comment: false
ignore:
  - "build/**"