name: Build

on:
  push:
    branches: [main]

  pull_request:

env:
  FLUTTER_VERSION: 3.16.9

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            build-option: "windows"
            artifact-path: "build/windows/x64/runner/Release"
            artifact-name: PitDisplay-Windows
    name: "[GUI] Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Install flutter deps
        if: ${{ matrix.build-option == 'linux' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true
          cache-path: ${{ runner.tool_cache }}/flutter/${{ matrix.build-option }}
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build app
        run: flutter build ${{ matrix.build-option }}
      
      - name: Zip release
        if: ${{ matrix.build-option == 'macos' }}
        run: |
          cd build/macos/Build/Products/Release
          zip -r BehaviorTreeEditor-macOS.zip behavior_tree_editor.app --symlinks
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}
